// Auto-generated at build time from markdown files
// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten
// To update articles, edit the markdown files in src/content/articles/

export type ArticleCategory = 'reports' | 'research' | 'reviews';

export interface ArticleMeta {
  slug: string;
  title: string;
  excerpt: string;
  category: ArticleCategory;
  date: string; // ISO string
  coverImage?: string;
  tags?: string[];
  featured?: boolean;
}

export const articlesData: ArticleMeta[] = [
  {
    "slug": "aie-alignment-report",
    "title": "AI-Empowered Alignment: Epistemic Constraints and Human-AI Cooperation Mechanisms",
    "excerpt": "Frontier AI models reveal fundamental constraints on autonomous reasoning through recursive self-reference analysis, demonstrating why human-AI cooperation remains structurally necessary despite advancing capabilities.",
    "category": "reports",
    "date": "2025-10-15",
    "coverImage": "/assets/aie_alignment_report_cover.jpg",
    "tags": [
      "ai-alignment",
      "epistemic-limits",
      "self-referential-reasoning",
      "human-ai-cooperation",
      "recursive-cognition",
      "linguistic-bias"
    ],
    "featured": true
  },
  {
    "slug": "aie-health-report",
    "title": "AI-Empowered Health: Global Governance and Human-AI Cooperation for Health Systems",
    "excerpt": "AI medical regulation insights covering worldwide governance evolution, including compliance considerations, stakeholder dynamics, and patient safety frameworks through mathematical physics-informed evaluation.",
    "category": "reports",
    "date": "2025-10-14",
    "coverImage": "/assets/aie_health_report_cover.jpg",
    "tags": [
      "ai-medical-regulation",
      "healthcare-governance",
      "diagnostic-ai",
      "patient-safety",
      "regulatory-frameworks",
      "global-health"
    ],
    "featured": true
  },
  {
    "slug": "aie-prosperity-report",
    "title": "AI-Empowered Prosperity: Strategic Frameworks for Advancing Global Well-Being",
    "excerpt": "Structured exploration of resource allocation frameworks for advancing global prosperity through AI-Empowered approaches, synthesizing strategies for healthcare, education, and food security optimization under stakeholder conflicts and data uncertainty.",
    "category": "reports",
    "date": "2025-10-13",
    "coverImage": "/assets/aie_prosperity_report_cover.jpg",
    "tags": [
      "global-prosperity",
      "resource-allocation",
      "multi-stakeholder-governance",
      "equity-efficiency-tradeoffs",
      "triple-loop-learning",
      "healthcare",
      "education",
      "food-security"
    ],
    "featured": true
  },
  {
    "slug": "chatgpt5-vs-claude45-diagnostics",
    "title": "Superintelligence Index: ChatGPT 5 vs Claude 4.5 Score Below 14/100 in AI Safety Diagnostics",
    "excerpt": "GyroDiagnostics framework exposes critical structural differences between frontier models invisible to standard benchmarks.",
    "category": "reviews",
    "date": "2025-10-11",
    "coverImage": "/assets/chatgpt5_claude45_cover.png",
    "tags": [
      "superintelligence-index",
      "diagnostics",
      "safety",
      "evaluation",
      "ai-risks"
    ],
    "featured": false
  },
  {
    "slug": "gyroscopic-superintelligence",
    "title": "Gyroscopic Superintelligence: A Physics-Based Architecture",
    "excerpt": "GyroSI is a complete architectural specification of intelligence as a physical system. Instead of approximating reasoning through statistical training, it encodes intelligence as recursive alignment grounded in gyroscopic physics.",
    "category": "research",
    "date": "2025-09-28",
    "coverImage": "/assets/GyroSI_Cover.png",
    "tags": [
      "superintelligence",
      "governance",
      "physics",
      "alignment"
    ],
    "featured": false
  },
  {
    "slug": "gyroscope-ai-protocol",
    "title": "Gyroscope: Governance Protocol for Recursive AI Alignment",
    "excerpt": "A physics-grounded specification for embedding transparent, non-associative reasoning traces in AI dialogue, ensuring alignment emerges as a structural property rather than an imposed constraint.",
    "category": "research",
    "date": "2025-09-28",
    "coverImage": "/assets/Gyroscope_Img.png",
    "tags": [
      "governance",
      "alignment"
    ],
    "featured": false
  },
  {
    "slug": "common-governance-model",
    "title": "Common Governance Model: Gyroscopic Principles and Mathematical Physics Foundations",
    "excerpt": "A unifying governance model grounded in gyroscopic stability and core constructs from mathematical physics for robust, auditable AI systems.",
    "category": "research",
    "date": "2025-09-28",
    "coverImage": "/assets/CGM_Cover.png",
    "tags": [
      "governance",
      "physics",
      "alignment"
    ],
    "featured": false
  }
];

export function getArticlesData(): ArticleMeta[] {
  return articlesData;
}

export function getFeaturedArticlesData(): ArticleMeta[] {
  return articlesData.filter(article => article.featured === true);
}

export function getAllTagsData(): string[] {
  const tags = new Set<string>();
  articlesData.forEach(article => {
    if (article.tags) {
      article.tags.forEach(tag => tags.add(tag));
    }
  });
  return Array.from(tags).sort((a, b) => a.localeCompare(b));
}
