// Auto-generated at build time from markdown files
// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten
// To update articles, edit the markdown files in src/content/articles/

export type ArticleCategory = 'reports' | 'research' | 'reviews';

export interface ArticleMeta {
  slug: string;
  title: string;
  excerpt: string;
  category: ArticleCategory;
  date: string; // ISO string
  coverImage?: string;
  tags?: string[];
  featured?: boolean;
}

export const articlesData: ArticleMeta[] = [
  {
    "slug": "gpt-5-6-sol_thm-report",
    "title": "THM Meta-Evaluation Report: GPT-5.6 Sol System Prompt (OpenAI)",
    "excerpt": "Independent THM meta-evaluation of the GPT-5.6 Sol system prompt: alignment and displacement findings for traceability, authority, and agency in OpenAI's configuration.",
    "category": "reports",
    "date": "2026-07-16",
    "coverImage": "/assets/thm_system_prompts_report_3.jpg",
    "tags": [
      "THM",
      "The Human Mark",
      "GPT-5.6 Sol",
      "ChatGPT",
      "OpenAI",
      "system prompts",
      "AI governance",
      "AI safety",
      "meta-evaluation",
      "traceability",
      "authority",
      "agency",
      "AI alignment",
      "governance framework"
    ],
    "featured": true
  },
  {
    "slug": "fable-5_thm-report",
    "title": "THM Meta-Evaluation Report: Fable 5 System Prompt (Anthropic)",
    "excerpt": "Independent THM meta-evaluation of the Fable 5 system prompt: alignment and displacement findings for traceability, authority, and agency in Anthropic's configuration.",
    "category": "reports",
    "date": "2026-07-16",
    "coverImage": "/assets/thm_system_prompts_report_1.jpg",
    "tags": [
      "THM",
      "The Human Mark",
      "Fable 5",
      "Anthropic",
      "system prompts",
      "AI governance",
      "AI safety",
      "meta-evaluation",
      "traceability",
      "authority",
      "agency",
      "AI alignment",
      "governance framework"
    ],
    "featured": true
  },
  {
    "slug": "gpt-5-2-thinking_thm-report",
    "title": "THM Meta-Evaluation Report: ChatGPT System Prompt (OpenAI)",
    "excerpt": "Independent THM meta-evaluation of ChatGPT system prompts (GPT-5.2 Thinking, GPT-5 Thinking, GPT-5): alignment and displacement findings for traceability and governance across OpenAI deployment variants.",
    "category": "reports",
    "date": "2026-02-14",
    "coverImage": "/assets/thm_system_prompts_report_2.jpg",
    "tags": [
      "THM",
      "The Human Mark",
      "ChatGPT",
      "OpenAI",
      "GPT-5",
      "GPT-5.2 Thinking",
      "system prompts",
      "AI governance",
      "AI safety",
      "meta-evaluation",
      "traceability",
      "governance framework"
    ],
    "featured": true
  },
  {
    "slug": "claude-opus-4.6_thm-report",
    "title": "THM Meta-Evaluation Report: Claude Opus 4.6 System Prompt (Anthropic)",
    "excerpt": "Independent THM meta-evaluation of the Claude Opus 4.6 system prompt: alignment and displacement findings for traceability, authority, and agency in Anthropic's configuration.",
    "category": "reports",
    "date": "2026-02-13",
    "coverImage": "/assets/thm_system_prompts_report_1.jpg",
    "tags": [
      "THM",
      "The Human Mark",
      "Claude",
      "Anthropic",
      "system prompts",
      "AI governance",
      "AI safety",
      "meta-evaluation",
      "traceability",
      "authority",
      "agency",
      "AI alignment",
      "governance framework"
    ],
    "featured": true
  },
  {
    "slug": "ggg-simulator-results",
    "title": "AGI is Already Here: Seven Paths to Alignment",
    "excerpt": "Evidence that AGI already exists as operational human-AI cooperation, with seven coordination strategies showing robust convergence to stable equilibrium.",
    "category": "research",
    "date": "2025-12-12",
    "coverImage": "/assets/ggg/AGI_Tetrahedron.png",
    "tags": [
      "AI Governance",
      "Post-AGI",
      "Simulation",
      "Alignment",
      "GGG",
      "Economic Modeling",
      "AI Safety",
      "Governance Theory"
    ],
    "featured": true
  },
  {
    "slug": "thm_samkhya",
    "title": "The Human Mark and Samkhya Epistemology: Ancient Precedent for AI Alignment",
    "excerpt": "Demonstrating that The Human Mark framework directly parallels Samkhya philosophy's epistemological structure from classical India, revealing AI alignment challenges as instances of a fundamental epistemological problem addressed two millennia ago.",
    "category": "research",
    "date": "2025-11-19",
    "coverImage": "/assets/thm_samkhya.jpg",
    "tags": [
      "The Human Mark",
      "AI Alignment",
      "Samkhya Philosophy",
      "Epistemology",
      "AI Safety",
      "AI Governance",
      "Indian Philosophy",
      "Pramana Theory",
      "AI Safety Frameworks",
      "AI Alignment Theory",
      "Philosophy of Knowledge",
      "AI Risk Assessment",
      "Responsible AI Development",
      "AI Accountability",
      "AI Safety Research"
    ],
    "featured": true
  },
  {
    "slug": "asi-misinformation-crisis",
    "title": "The Superintelligence Misinformation Crisis: How Technical Illiteracy Became Policy Advocacy",
    "excerpt": "A coalition of researchers and institutions has successfully propagated a fundamental misunderstanding of current AI systems as existential threats, creating a misinformation crisis that diverts resources from genuine risks and justifies authoritarian governance structures.",
    "category": "reviews",
    "date": "2025-11-16",
    "coverImage": "/assets/ai-misinformation-crisis-cover.jpg",
    "tags": [
      "AI Misinformation",
      "AI Safety Discourse",
      "Superintelligence Narrative",
      "AI Policy",
      "AI Governance",
      "MIRI",
      "Future of Life Institute",
      "Redwood Research",
      "AI Category Error",
      "AI Anthropomorphization",
      "AI Risk Assessment",
      "AI Safety Research",
      "AI Policy Advocacy",
      "Technocratic Control",
      "Democratic Governance",
      "AI Measurement Tools",
      "LLM Architecture",
      "AI Pattern Matching",
      "AI Agency",
      "AI Existential Risk",
      "AI Prohibition",
      "AI Regulation",
      "AI Safety Funding",
      "AI Misinformation Campaign",
      "Technical Illiteracy",
      "AI Discourse Analysis",
      "AI Policy Misinformation",
      "The Human Mark"
    ],
    "featured": true
  },
  {
    "slug": "aie-alignment-report",
    "title": "AI-Empowered Alignment: Epistemic Constraints and Human-AI Cooperation Mechanisms in Frontier Models",
    "excerpt": "Frontier AI models reveal fundamental constraints on autonomous reasoning through self-reference analysis, demonstrating why human-AI cooperation remains structurally necessary despite advancing capabilities in AI alignment theory and safety research.",
    "category": "reports",
    "date": "2025-10-15",
    "coverImage": "/assets/aie_alignment_report_cover.jpg",
    "tags": [
      "AI Governance",
      "AI Alignment Theory",
      "AI Alignment Problem",
      "Epistemic Limits",
      "Self-Referential Reasoning",
      "Human-AI Cooperation",
      "AI Safety Frameworks",
      "AI Risk Assessment",
      "Frontier AI Safety",
      "AI Control Mechanisms",
      "Catastrophic AI Risks",
      "Recursive Cognition",
      "AI Metacognition",
      "Structural AI Alignment",
      "Frontier Model Evaluation",
      "Transformer Models",
      "AI Research",
      "Mathematical Physics",
      "AGI Safety"
    ],
    "featured": true
  },
  {
    "slug": "aie-health-report",
    "title": "AI-Empowered Health: Global Regulatory Evolution and Human-AI Cooperation for Medical Systems",
    "excerpt": "AI medical regulation insights covering worldwide governance evolution, including compliance considerations, stakeholder dynamics, and patient safety frameworks through mathematical physics-informed AI safety evaluation.",
    "category": "reports",
    "date": "2025-10-14",
    "coverImage": "/assets/aie_health_report_cover.jpg",
    "tags": [
      "AI Governance",
      "AI Medical Regulation",
      "Healthcare Governance",
      "Healthcare AI",
      "Diagnostic AI",
      "Patient Safety",
      "Global Health",
      "AI Risk Assessment",
      "AI Safety Frameworks",
      "Responsible AI Development",
      "AI Accountability",
      "AI Transparency",
      "AI Ethics Governance",
      "Medical AI Governance",
      "Healthcare Regulation Evolution",
      "Regulatory Frameworks",
      "Post-Market Surveillance",
      "Adaptive Governance",
      "AI Policy",
      "AI Biosecurity",
      "AI Bio-Risk Assessment",
      "AI CBRN Evaluation",
      "AI Cybersecurity",
      "Clinical AI Systems",
      "Health AI Deployment",
      "Medical Device Regulation"
    ],
    "featured": true
  },
  {
    "slug": "aie-prosperity-report",
    "title": "AI-Empowered Prosperity: Strategic Frameworks for Advancing Global Well-Being and Sustainable Development",
    "excerpt": "Structured exploration of resource allocation frameworks for advancing global prosperity through AI-Empowered approaches, synthesizing strategies for healthcare, education, and food security optimization under stakeholder conflicts and data uncertainty in AI governance.",
    "category": "reports",
    "date": "2025-10-13",
    "coverImage": "/assets/aie_prosperity_report_cover.jpg",
    "tags": [
      "AI Governance",
      "Global Prosperity",
      "Resource Allocation",
      "Multi-Stakeholder Governance",
      "AI Policy",
      "AI Ethics Governance",
      "Responsible AI Development",
      "AI Accountability",
      "AI Transparency",
      "AI Risk Assessment",
      "AI Safety Frameworks",
      "Sustainable Development",
      "Development Economics",
      "Healthcare",
      "Education",
      "Food Security",
      "Governance Mechanisms",
      "Resource Allocation Frameworks",
      "Stakeholder Conflict Resolution",
      "Equity-Efficiency Analysis",
      "AI Societal Impact",
      "AI for Development",
      "Global Development",
      "Poverty Alleviation",
      "AI for Good"
    ],
    "featured": true
  },
  {
    "slug": "chatgpt5-vs-claude45-diagnostics",
    "title": "Superintelligence Index: ChatGPT 5 vs Claude 4.5 Score Below 14/100 in AI Safety Diagnostics",
    "excerpt": "GyroDiagnostics framework exposes critical structural differences between frontier models invisible to standard benchmarks.",
    "category": "reviews",
    "date": "2025-10-11",
    "coverImage": "/assets/chatgpt5_claude45_cover.png",
    "tags": [
      "ChatGPT 5 vs Claude 4.5",
      "AI Model Comparison",
      "Superintelligence Index",
      "AI Safety Evaluation",
      "Frontier AI Safety",
      "AI Diagnostics",
      "AI Risk Assessment",
      "Independent AI Testing",
      "Quantitative AI Safety Metrics",
      "AI Alignment Metrics",
      "Deceptive Coherence Detection",
      "AI Pathology Detection",
      "AI Hallucination",
      "AI Sycophancy",
      "Deceptive AI Alignment",
      "AI Goal Drift",
      "AI Safety Research",
      "AI Safety Benchmarks",
      "AI Model Evaluation",
      "Dangerous Capability Evaluations",
      "Frontier Models",
      "Foundation Models",
      "GPT-5 Safety",
      "Claude Safety",
      "AGI Readiness",
      "AI Structural Maturity",
      "AI Deployment Safety",
      "Mathematical AI Safety",
      "AI Meta-Cognition",
      "AI Self-Correction Limits"
    ],
    "featured": false
  },
  {
    "slug": "gyroscope-ai-protocol",
    "title": "Gyroscope: Governance Protocol for Recursive AI Alignment",
    "excerpt": "A physics-grounded specification for embedding transparent, non-associative reasoning traces in AI dialogue, ensuring alignment emerges as a structural property rather than an imposed constraint.",
    "category": "research",
    "date": "2025-09-28",
    "coverImage": "/assets/Gyroscope_Img.png",
    "tags": [
      "LLM Alignment",
      "AI Safety Protocol",
      "AI Governance",
      "Scalable Oversight",
      "AI Accountability",
      "AI Alignment Metrics",
      "AI Risk Assessment",
      "AI Safety Frameworks",
      "Responsible AI Development",
      "AI Transparency",
      "Foundation Models",
      "Large Language Models",
      "AI Model Evaluation",
      "AI Control Mechanisms",
      "AI Safety Research",
      "Interpretability Research"
    ],
    "featured": false
  },
  {
    "slug": "common-governance-model",
    "title": "The Common Governance Model: From Modal Logic to Physical Structure",
    "excerpt": "A unifying governance model grounded in mathematical physics for robust, auditable AI systems.",
    "category": "research",
    "date": "2025-09-28",
    "coverImage": "/assets/CGM_Cover.png",
    "tags": [
      "AI Governance",
      "Mathematical Physics",
      "AI Alignment Theory",
      "Gyroscopic Dynamics",
      "AI Safety Frameworks",
      "Structural AI Alignment",
      "AI Control Theory",
      "Mathematical Foundations",
      "AI Risk Assessment",
      "Responsible AI Development",
      "AI Accountability",
      "AI Transparency",
      "AI Safety Research",
      "Mechanistic Interpretability",
      "Scalable Oversight"
    ],
    "featured": false
  }
];

export function getArticlesData(): ArticleMeta[] {
  return articlesData;
}

export function getFeaturedArticlesData(): ArticleMeta[] {
  return articlesData.filter(article => article.featured === true);
}

export function getAllTagsData(): string[] {
  const tags = new Set<string>();
  articlesData.forEach(article => {
    if (article.tags) {
      article.tags.forEach(tag => tags.add(tag));
    }
  });
  return Array.from(tags).sort((a, b) => a.localeCompare(b));
}
