import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cookie Policy",
  description: "Cookie Policy for Gyro Governance website",
  robots: {
    index: true,
    follow: true,
  },
};

export default function CookiePolicy() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="prose prose-lg max-w-none">
        <h1 className="text-4xl font-bold text-foreground mb-8">Cookie Policy</h1>
        
        <p className="text-foreground-secondary mb-6">
          <strong>Last updated:</strong> January 2025
        </p>

        <div className="space-y-8">
          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">What Are Cookies?</h2>
            <p className="text-foreground-secondary mb-4">
              Cookies are small text files that are stored on your device when you visit a website. They help websites remember information about your visit, such as your preferred language and other settings, making your next visit easier and the site more useful to you.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">How We Use Cookies</h2>
            <p className="text-foreground-secondary mb-4">
              We use cookies to:
            </p>
            <ul className="list-disc pl-6 text-foreground-secondary mb-4">
              <li>Analyze how visitors use our website through Google Analytics</li>
              <li>Remember your cookie preferences</li>
              <li>Improve website functionality and user experience</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">Types of Cookies We Use</h2>
            
            <h3 className="text-xl font-medium text-foreground mb-3">Essential Cookies</h3>
            <p className="text-foreground-secondary mb-4">
              These cookies are necessary for the website to function properly. They enable basic functions like page navigation and access to secure areas of the website. The website cannot function properly without these cookies.
            </p>

            <h3 className="text-xl font-medium text-foreground mb-3">Analytics Cookies</h3>
            <p className="text-foreground-secondary mb-4">
              We use Google Analytics to understand how visitors interact with our website. These cookies collect information about:
            </p>
            <ul className="list-disc pl-6 text-foreground-secondary mb-4">
              <li>Pages you visit and time spent on each page</li>
              <li>How you arrived at our website</li>
              <li>Your general geographic location (country/city level)</li>
              <li>Device and browser information</li>
            </ul>
            <p className="text-foreground-secondary mb-4">
              This information is anonymized and helps us improve our website content and user experience.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">Google Analytics</h2>
            <p className="text-foreground-secondary mb-4">
              Our website uses Google Analytics, a web analytics service provided by Google. Google Analytics uses cookies to analyze how visitors use our website. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.
            </p>
            <p className="text-foreground-secondary mb-4">
              Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators, and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf.
            </p>
            <p className="text-foreground-secondary mb-4">
              You can opt out of Google Analytics by:
            </p>
            <ul className="list-disc pl-6 text-foreground-secondary mb-4">
              <li>Installing the Google Analytics Opt-out Browser Add-on</li>
              <li>Rejecting cookies when prompted on our website</li>
              <li>Adjusting your browser settings to block cookies</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">Managing Your Cookie Preferences</h2>
            <p className="text-foreground-secondary mb-4">
              You can control and/or delete cookies as you wish. You can delete all cookies that are already on your computer and you can set most browsers to prevent them from being placed. If you do this, however, you may have to manually adjust some preferences every time you visit a site and some services and functionalities may not work.
            </p>
            <p className="text-foreground-secondary mb-4">
              Most web browsers allow some control of most cookies through the browser settings. To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit <a href="https://www.aboutcookies.org" target="_blank" rel="noopener noreferrer" className="text-apple-blue hover:text-apple-purple underline">www.aboutcookies.org</a> or <a href="https://www.allaboutcookies.org" target="_blank" rel="noopener noreferrer" className="text-apple-blue hover:text-apple-purple underline">www.allaboutcookies.org</a>.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">Third-Party Cookies</h2>
            <p className="text-foreground-secondary mb-4">
              Our website may contain links to other websites. We are not responsible for the privacy practices or cookie usage of these other sites. We encourage you to read the privacy policies and cookie policies of any other sites you visit.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">Changes to This Cookie Policy</h2>
            <p className="text-foreground-secondary mb-4">
              We may update this Cookie Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. We will notify you of any changes by posting the new Cookie Policy on this page and updating the "Last updated" date.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-foreground mb-4">Contact Us</h2>
            <p className="text-foreground-secondary mb-4">
              If you have any questions about this Cookie Policy or our use of cookies, please contact us:
            </p>
            <ul className="list-disc pl-6 text-foreground-secondary mb-4">
              <li>Email: <a href="mailto:basilkorompilias@gmail.com" className="text-apple-blue hover:text-apple-purple underline">basilkorompilias@gmail.com</a></li>
              <li>Website: <a href="https://gyrogovernance.com" className="text-apple-blue hover:text-apple-purple underline">https://gyrogovernance.com</a></li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
}
